[workspace]
resolver = "3"
members = ["common", "publisher", "consumer"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
google-cloud-pubsub = {version = "0.30.0"}
thiserror = {version = "2.0.17"}
dotenv = {version = "0.15.0"}
tracing = {version = "0.1.43"}
tracing-subscriber = {version = "0.3.22"}
tonic = {version = "0.12"}
google-cloud-googleapis = {version = "*"}
serde = {version = "1.0.228"}
serde_json = {version = "1.0.145"}
uuid = {version = "1.19.0", features = ["v7", "serde"]}
