FROM rust:1.90-bookworm AS builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release -p publisher

FROM ubuntu:latest AS runtime
COPY --from=builder /usr/src/app/target/release/publisher /usr/local/bin/publisher

RUN apt-get update && apt-get install -y curl
EXPOSE 8080
CMD ["publisher"]
